/*******************************************************************************
 * @file bsp_logger.h
 *
 * @author Alexy Torres Aurora Dugo
 *
 * @date 29/06/2020
 *
 * @version 1.0
 *
 * @brief Board logger manager.
 *
 * @details Board logger manager. This module contains the routines interface
 * used to output the loggs generated by the kernel.
 ******************************************************************************/

#ifndef __BOARD_LOGGER_H__
#define __BOARD_LOGGER_H__

#include "stdint.h"
#include "stddef.h"
#include "error_types.h"

/*******************************************************************************
 * DEFINES
 ******************************************************************************/

/*******************************************************************************
 * STRUCTURES
 ******************************************************************************/

/*******************************************************************************
 * FUNCTIONS
 ******************************************************************************/

/**
 * @brief Writes a log message to the log buffer or log output.
 * 
 * @details Writes a log message to the log buffer or log output. The 
 * implementation of the buffer or output is free and left to the BSP design 
 * choices.
 * 
 * @param[in] str The message to be written to the log buffer or output.
 * @param[in] length The size of the message to be written.
 */
void bsp_logger_write_hook (const char* str, const size_t length);

#endif /* #ifndef __BOARD_LOGGER_H__ */