/*******************************************************************************
 * @file error_types.inc
 *
 * @author Alexy Torres Aurora Dugo
 *
 * @date 24/06/2020
 *
 * @version 1.0
 *
 * @brief Kernel error types definitions.
 *
 * @details Kernel error types definitions. This modules defines the structures,
 * enumerations and macros used in case of error.
 ******************************************************************************/

/**
 * @brief Enumerate the possible errors codes happening in the kernel.
 */
.equ NO_ERROR, 0
.equ ERROR_INVALID_PARAM, 1