/*******************************************************************************
 * @file bsp_logger.c
 *
 * @author Alexy Torres Aurora Dugo
 *
 * @date 29/06/2020
 *
 * @version 1.0
 *
 * @brief Board logger manager.
 *
 * @details Board logger manager. This module contains the routines interface
 * used to output the loggs generated by the kernel.
 ******************************************************************************/

#include "error_types.h"
#include "bsp_logger.h"
#include "serial.h"
#include "stddef.h"
#include "stdint.h"

/*******************************************************************************
 * Private Data
 ******************************************************************************/

/*******************************************************************************
 * Private functions
 ******************************************************************************/

/*******************************************************************************
 * Public functions
 ******************************************************************************/

void bsp_logger_write_hook (const char* str, const size_t length)
{
    /* Writes the log to the serial output */
    serial_write(str, length);
}